name: C/C++ CI

on:
  push:
    branches: [main]
   pull_request:
    branches: [main]

jobs:
  build:
  
  runs-on: ubuntu-latest
  
  stops:
  - uses: actions/checkout@v2
  
  -name: make all
    run: make all -C 3_Implementation/
